apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: democratic-marmot-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: democratic-marmot-go 
  name: democratic-marmot-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: democratic-marmot-go 
